### PR TITLE
Prepare release of polymer-project-config 3.4.0

### PR DESCRIPTION
**Pull request by usergenic**
* Minor release 3.3.0 -> 3.4.0 because update to the type value of bundle is significant enough to warrant IMO.
* Modified the `bundle` property in project build options to support the subset of `polymer-bundler` options which can be serialized in a JSON file.
* `bundle` property used to just be a `boolean`.  Now it can be boolean OR an object bag of settings matching (most-of) the polymer-bundler constructor options:
```typescript
  bundle?: boolean|{

    /** URLs of files and/or folders that should not be inlined. */
    excludes?: string[],

    /** Inline external CSS file contents into <style> tags. */
    inlineCss?: boolean,

    /** Inline external Javascript file contents into <script> tags. */
    inlineScripts?: boolean,

    /** Rewrite element attributes inside of templates when inlining html. */
    rewriteUrlsInTemplates?: boolean,

    /** Create identity source maps for inline scripts. */
    sourcemaps?: boolean,

    /**
     * Remove all comments except those tagged '@license', or starting with
     * `<!--!` or `<!--#`, when true.
     */
    stripComments?: boolean,
  };
```
* Note: this new config is compatible with existing configs in that the only handling of the `bundle` option thus-far has been in the `polymer-cli` which does general truthiness check one value, so introducing an Object will just be treated as `true` for purposes of un-upgraded versions of the CLI so this is NOT a BREAKING change.

### CODE REVIEW

**Comment by justinfagnani** [comment]
Looks like this is a docs impacting release, or the release of bundler/cli that includes this will be. Do we have a docs issue?

**Comment by arthurevans** [comment]
Tagging @katejeffreys can you take this update? Create a docs issue if we don't have one and update the `polymer.json` spec?

**Comment by arthurevans** [comment]
... would probably also be a good opportunity to do a quick audit of CLI options/polymer.json syntax and make sure the docs are up to date with the latest.

**Comment by justinfagnani** [comment]
@arthurevans @katejeffreys this release or polymer-project-config doesn't actually enable the new config until we release a version of Bundler that uses it. Can we get approval here and sync docs with the Bundler/CLI release?

**Comment by usergenic** [comment]
Clarification: bundler won't require an update, just polymer-cli.  These settings are already a part of bundler, they are just being exposed for the first time through the config so that polymer-cli can offer access to the options so users don't have to completely switch to writing gulp pipelines for otherwise conventional builds.

**Comment by usergenic** [comment]
The chief driver for this change was the ability to specify the `rewriteTemplatesInUrls` option, which defaults to `false` but used to be `true` for polymer 1.x.  Now people with existing 1.x projects that have elements that depend on the old vulcanize behavior of rewriting url attributes that were in their templates have to set this to true.  This was basically a breaking change that polymer 2.x introduced.

**Comment by usergenic** [comment]
@arthurevans @katejeffreys I created a docs issue https://github.com/Polymer/docs/issues/2215 to ensure coverage for this change.  I can has LGTM?

**Comment by justinfagnani** [comment]
Since there's now a docs issue, LGTM from me. Ping @wmginsberg @graynorton @arthurevans @katejeffreys

**Comment by usergenic** [comment]
given 24 hours since justin's LGTM I'm merging.

**Comment by katejeffreys** [comment]
Thanks for this @usergenic and @justinfagnani. LGTM and I will try to be more on-the-ball with these in future.

**Pull request merged**
