### PR TITLE
New: Add minSeverity property to lint options

### PR DESCRIPTION
**Pull request by stramel**
- [x] CHANGELOG.md has been updated

This will need to precede https://github.com/Polymer/polymer-cli/pull/723 which is adding the use-case for it.

Any help on description wording/explanation would be wonderful! Thanks!

### CODE REVIEW

**Comment by justinfagnani** [comment]
We need to hold on the PRs for a second and discuss this issue and possibly approaches. I for one want to understand why this isn't handled outside of the CLI, for instance by using `;` instead of `&&` to chain commands when you don't want a lint warning to prevent further steps.

**Comment by stramel** [comment]
@justinfagnani This also controls what is output. Currently, there is no way to change that. So there could be Info messages that I can never see and inversely, I can't limit it to just error messages.

Also, for failure, my main case here is CI server would I then be required to always chain `polymer lint` something like `polymer lint || true` to prevent it from failing? What if I want it to fail on Error cases but not Warnings in my CI?

**Comment by rictic** [comment]
IMO the biggest outstanding issue here is the inability to exclude files or sections of files from lint errors, and that should be our first goal here.

**Comment by stramel** [comment]
@FredKSchott has a PR out for lint directives https://github.com/Polymer/polymer-linter/pull/85

and I just added an issue the other day for ignoring/excluding paths https://github.com/Polymer/polymer-linter/issues/88

**Comment by FredKSchott** [comment]
Sorry for the late response everyone, I've been traveling the last ~2 weeks.

@stramel can you give an example of a warning that you would like lint to succeed (exit code `0`) on? We're having trouble thinking up a good use-case for what you're describing (ignoring all warnings). 

In general, a blanket `minSeverity` option to ignore all warnings makes it our responsibility to decide what lint issues should be "blocking" (exit code `1`) vs. "not blocking". That's a game we shouldn't get into, since we'll never make everyone happy. 

Something that I had wanted to see was the ability to report but not "block" for certain lint rules. But this is a small improvement over `ignoreWarnings` which is already supported.

**Comment by stramel** [comment]
@FredKSchott I guess one case is a property not being declared in the properties section. It works without declaring them and is a warning so I don't see why this would be "blocking".

**Comment by ankon** [comment]
Use case for making warnings less severe: I'm setting up CI for a couple of polymer 2.x components. These components have been reviewed, work in production, and are generally up to standards. But, `polymer lint` finds them "broken":
- `warning [unknown-superclass] - Unable to resolve superclass parent`: Actually, this looks like a misunderstanding, the code in question is a function and the parent is provided as argument of that function.
- `warning [set-unknown-attribute] - collaborne-tool-bright-stars-overview elements do not have a property named language. Consider instead:  lang`: Well, I considered, and for now we decided to keep these separate.
- `warning [databind-with-unknown-property] - localize is not declared and is only read from, never written to. If it's part of the element's API it should be a declared property.`: It is declared by a mixin, but as per the first item the linter chokes on that.
- `warning [databind-with-unknown-property] - nrSelectedIdeas is not declared or used more than once. Did you mean: ideas`: Same. Linter chokes, suggestion is reasonable for a machine, but I know it is wrong.

In the current state I have two options:
1. Drop `polymer lint` invocation, and just hope that things work out.
2. Keep `polymer lint`, but as `polymer lint || true` to prevent build failures. Again, hoping that things will be fine and no-one introduces errors they don't check for in other places. 

"Hope is not a strategy" though, so I really would like to be able to have `polymer lint` report warnings as "non-blocking", and errors as "blocking". Either by me configuring that (with a command-line argument as well, please!), or by this being the default - precendents exist since a long time (-Werror switches for gcc, for example.)

**Comment by ankon** [comment]
I hate being the person bumping tickets just to ask for updates, but ... any update here? Anything that we can do to get things forward?

**Review by justinfagnani — APPROVED** [review]

**Comment by justinfagnani** [comment]
@stramel this needs a rebase

**Comment by stramel** [comment]
@justinfagnani Did you change your mind on this issue? I believe last real opinion from you was [here](https://github.com/Polymer/polymer-cli/pull/709#issuecomment-299062021) and sounded against this approach. 

I will be happy to rebase and get this rolling again if you are good with it.

**Pull request closed without merging**
